version: "3.7"
services:
  publisher:
    build:
      context: publisher/
    network_mode: "host"
  subscriber:
    build:
      context: subscriber/
    network_mode: "host"
  broker:
    container_name: broker
    image: redis
    network_mode: "host"
    ports: 
      - "6379:6379"

